influxdb:
  image: influxdb:2.7
  container_name: influxdbmodule2
  restart: unless-stopped

  ports:
    - "8086:8086"

  volumes:
    - influxdb_data:/var/lib/influxdb2

  environment:
    DOCKER_INFLUXDB_INIT_MODE: setup
    DOCKER_INFLUXDB_INIT_USERNAME: admin
    DOCKER_INFLUXDB_INIT_PASSWORD: adminadmin123
    DOCKER_INFLUXDB_INIT_ORG: openhab
    DOCKER_INFLUXDB_INIT_BUCKET: openhab
    DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: DYV2UyIOUawJZanlsex_FzasHU30zWmOgKyxMWFiICP-G5FF66VrWykaZ43WdWDM-yJMkxwwHzkhT9YNQu7NXQ==

  networks:
    - smart_home_net

  healthcheck:
    test: ["CMD-SHELL", "wget -qO- http://localhost:8086/health || exit 1"]
    interval: 20s
    timeout: 10s
    retries: 10
    start_period: 30s
