services:
  mosquitto:
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 1883"]
      interval: 5s
      timeout: 3s
      retries: 10

  test_runner:
    build:
      context: .
      dockerfile: tests/Dockerfile

    depends_on:
      mosquitto:
        condition: service_healthy

    networks:
      - smart_home_net

    environment:
      - MQTT_HOST=mosquitto

    command: >
      sh -c "
        echo 'Waiting for MQTT...';
        python - <<EOF
    import socket, time
    for _ in range(30):
        try:
            s = socket.create_connection(('mosquitto', 1883), 2)
            s.close()
            print('MQTT ready')
            break
        except:
            time.sleep(2)
    else:
        raise SystemExit('MQTT not available')
    EOF
        pytest -q tests/integration
      "
