services:
  test_runner:
    build:
      context: .
      dockerfile: tests/Dockerfile
    container_name: integration_test_runner

    depends_on:
      mosquitto:
        condition: service_started
      influxdb:
        condition: service_started
      edge_ai:
        condition: service_started
      sensor_simulator:
        condition: service_started

    networks:
      - smart_home_net

    environment:
      MQTT_HOST: mosquitto

    command: ["pytest", "-q", "tests/integration"]
