apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    editable: true

    jsonData:
      version: Flux
      organization: openhab
      defaultBucket: openhab

    secureJsonData:
      token: DYV2UyIOUawJZanlsex_FzasHU30zWmOgKyxMWFiICP-G5FF66VrWykaZ43WdWDM-yJMkxwwHzkhT9YNQu7NXQ==